### PR TITLE
Fix filtered widgets in mailer

### PR DESCRIPTION
**Pull request by cekk**
The mailer action collects all available widgets and try to render them without some filtering.
Then, he filters the fields and get only the wanted fields.

When we use for example a captcha field, it will break when we try to render it, so i filtered also the widgets with only selected fields. In this case the mailer won't break.

### CODE REVIEW

**Comment by cekk** [comment]
Any news about this pr?
Who's the maintainer of this product?

**Comment by tkimnguyen** [comment]
@cekk looking at who's been contributing the most, I'd say Tom, Jens, and Peter this year. But I'm paying some attention...

**Comment by tkimnguyen** [comment]
Thanks for adding this code and a test! Would you mind adding something to the documentation too? I'd like to see us adding at least SOME documentation for every new feature as it is being added.

**Comment by tomgross** [comment]
Since this is more a bug fix than a feature I merge to not block a production release.

**Pull request merged**
