### PR TITLE
Add support for Plone 6

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by frapell** [comment]
This is related to https://github.com/collective/collective.easyform/issues/319

**Review by Arhell — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]
I have tested it on the coredev 6 ES6 config. Seems to work fine. Thanks!
If this is merged, it only works on Plone 6, right? It is a breaking change then, so it should be a major release.
For me, this can be merged once the Plone core ES6 stuff is merged. But the tests should be green first.

**Comment by pbauer** [comment]
I have just tested this branch on Plone 5.2 (with py3) and it works fine.

**Comment by pbauer** [comment]
This is ready to merge now. Works in Plone 5.2 (py2/py3) and Plone 6.

**Comment by pbauer** [comment]
The fallback to pat-schemaeditor is a teaxtarea field which works fine in Plone 5.2 and is enough for most use-cases anyway imho. 
I'll fix the setup.py and add tests for 5.2 on 3.6.

**Comment by pbauer** [comment]
@mauritsvanrees: done. https://github.com/collective/collective.easyform/pull/261 should be good to merge now.

**Pull request merged**
