### PR TITLE
Fix `IEasyFormWidget` marker for GroupForm widgets

### LINKED ISSUE #370: Conditional field support does not work for fields inside fieldsets
Somehow the data-attributes needed for pat-depends are missing when fields are moved into fieldsets.

### PR DESCRIPTION
**Pull request by petschki**
fixes #370 

also updated GHA to mxdev setup

### CODE REVIEW

**Review by MrTango — APPROVED** [review]
hard to read ;), but looks ok

**Comment by petschki** [comment]
Sorry ;) this is the main part. looping through the group widgets and apply the interface https://github.com/collective/collective.easyform/pull/374/commits/d596b11637558223963e86f17d5a7e409f570387 ... the rest is maintenance

**Comment by MrTango** [comment]
LGTM

**Comment by mauritsvanrees** [comment]
This works and is better than my own attempt in PR #389. I did not notice this PR and related issue when I started working on that. :-/

There are some conflicting files. I will have a look. Maybe I will end up cherry-picking your main commit in a different PR.

**Comment by mauritsvanrees** [comment]
I close this in favour of my PR #393 which cherry-picks a few commits from here. Feel free to disagree and reopen of course.
Thanks for the fix!

**Pull request closed without merging**
