### PR TITLE
Fix templates to match Plone 6 master template

### PR DESCRIPTION
**Pull request by szakitibi**
The current `@@fields`, `@@actions` forms and the related modelleditor views fill the `content` slot of the master template, which is changed with Plone 6, see comment from `Products.CMFPlone`:

> Please note that this template fills the "content" slot instead of the "main" slot, this is done so we can provide stuff like the content tabs. This also means that we have to supply things that are normally present from main_template. [[source]](https://github.com/plone/Products.CMFPlone/blob/6.0.11/Products/CMFPlone/browser/templates/author.pt#L18-L23)

The `model_listing.pt` also inserts additional `#edit-bar` div and a duplicate portal message. See it on https://classic.demo.plone.org/ by creating an EasyForm, and opening the fields actions. A search for `#edit-bar` in the console will have multiple results. The duplicate portal message does not show up, since the master template one already dumps the messages.

image

The proposed changes remove the duplicate edit bar and portal messages, while updating the templates to match [Plone 6 master template](https://github.com/plone/Products.CMFPlone/blob/6.0.11/Products/CMFPlone/browser/templates/main_template.pt#L79-L85), while providing the things normally present in main template (e.g. `article#content`).

Note: The templates could be further simplified if the `main` slot is used, but it would add the footer and `plone.belowcontent` to the views.

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks!

**Comment by mauritsvanrees** [comment]
The GitHub Actions all failed, but I can't see why, probably because it is too long ago.
Can you either rebase on master or manually trigger a rerun of the actions?  I can't do that, probably because your code is on a fork.

**Comment by szakitibi** [comment]
> The GitHub Actions all failed, but I can't see why, probably because it is too long ago. Can you either rebase on master or manually trigger a rerun of the actions? I can't do that, probably because your code is on a fork.

The checks complained about Node 16, but I could not trigger a rerun either.

Used GitHub's convenient "Update branch" button, which simply merged `collective:master` into the `plone6_template_fix` branch. So it is not a rebase, but hope it works as well.

**Comment by mauritsvanrees** [comment]
Thanks!

**Pull request merged**
