### PR TITLE
Migrate ReCaptcha field to not required

### PR DESCRIPTION
**Pull request by ThibautBorn**
context: ReCaptcha fields may not be required in easyform

### CODE REVIEW

**Review by gotcha — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
I don't get it.  I would think that ReCaptcha fields should always be required, otherwise they do not work.  At least, that is what I expect.
Can you explain?

**Comment by ThibautBorn** [comment]
Yes, that was my assumption as well. But is is stated in the readme [here ](https://github.com/collective/collective.easyform/blob/master/README.rst?plain=1#L175). And when I tested it, the recpatcha would indeed not pass if it was required. While it is enforced even when it is not checked.

By default the recaptchas were required in Plone 4, so all forms with recaptchas broke in Easyforms if left unchanged.

**Review by mauritsvanrees — APPROVED** [review]
Ah, thanks for the explanation.

**Comment by mauritsvanrees** [comment]
Released as 4.1.4.

**Pull request merged**
