### PR TITLE
Tomgross setuptools hell

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by gforcada** [comment]
@tomgross I feel your pain, I spent a full day just to get it working on jenkins (for a new node). We end up pinning setuptools to ``33.1.1``, which is the last version that still vendors all its dependencies, so less pins on requirements.txt :-)

**Comment by tomgross** [comment]
@gforcada thanks for the hint. I was copy and pasting from http://dist.plone.org/release/5.1b3/versions.cfg

**Comment by thet** [comment]
I always explicitly unpin like:
``
[versions]
zc.buildout =
setuptools =
```

I have the feeling that in coredev and plone releases would help.

**Comment by gforcada** [comment]
@thet after spending a whole weekend to set up a new jenkins node, I can firmly say **no** that's a ticking bomb that you are setting yourself.

Up until setuptools 35 it was probably fine, as setuptools was vendoring all its dependencies. If you are not using virtualenv to install setuptools and your project to run the tests, then this unpinning is going to shot yourself on the foot at any point.

**Comment by tomgross** [comment]
can someone review/merge this please, to allow further development.

**Pull request merged**
