### PR TITLE
Forward ports from 1.x branch

### PR DESCRIPTION
**Pull request by fredvd**
Forward port "E-mail adress invalid" translation and add css class to thankspage template.

### CODE REVIEW

**Comment by tkimnguyen** [comment]
@fredvd is this still a good, valid PR?

**Comment by fredvd** [comment]
@tkimnguyen AFAIK yes. This small feature has been in production in the 1.x branch on some Plone 4 sites for 5 months, there it was already merged to master.

**Comment by fredvd** [comment]
to be able to style the thanks page when you use css injection

**Comment by tkimnguyen** [comment]
Yes it was good to use the polite way :) but apparently not a lot of people working on this. Thx for merging

**Pull request merged**
