### PR TITLE
CSV download is not user friendly for users that do not use comma as list delimiter

### PR DESCRIPTION
**Pull request by gotcha**
Enable specifying the delimiter before downloading
Add a registry option in order to setup proper default delimiter.

### CODE REVIEW

**Comment by gotcha** [comment]
@mauritsvanrees Can you confirm that 5.2.3-pending.cfg can go away ?

**Comment by gotcha** [comment]
@smcmahon Sorry that I disturbed you. Hoping all is fine for you. Regards !

**Comment by gotcha** [comment]
#265 might be closed if this is merged. I'll remove test-5.2.3-pending if Maurits confirms that it can go away as I suspect it.

**Comment by gotcha** [comment]
@mauritsvanrees Thanks for quick answer ! I just removed `test-5.2.3-pending.cfg`.

**Review by jensens — APPROVED** [review]

**Comment by fredvd** [comment]
@gotcha  @jensens  A new field was edit to the registry records, csv_delimiter, but there is no upgrade step for plone.app.registry yet.  Breaks the control panel on existing sites.

**Comment by fredvd** [comment]
Will be fixed in branch for hcaptcha support

**Pull request merged**
