### PR TITLE
Few UX improvements

### PR DESCRIPTION
**Pull request by frapell**
## When adding/editing fields on a form
* No need for the "Unload protection"
* When clicking the button "Done" at the bottom, send the editor back to the form, instead of remaining in the "Form fields"

## When adding/editing actions on a form
* When clicking the button "Save" at the bottom, send the editor back to the form, instead of remaining in the "Edit actions"

### CODE REVIEW

**Comment by laulaz** [comment]
@frapell I just tested this pull request. Works fine for me.

I just have one concern : as a form editor, I don't understand why actions edit form and fields edit form do not behave the same.

On actions edit form, you can 
 - **Save (--> go back to the easyform)**
 - Edit XML Actions Model
 
 On  fields edit form, you can 
 - **Done (--> go back to the easyform)**
 - **Save Defaults** (why not "Save" ?)
 - Edit XML Actions Model
 
Wouldn't it be better to harmonize the buttons & effects ?  or maybe I am missing something ?

**Comment by frapell** [comment]
@laulaz Thanks for your feedback!
Yeah, maybe "Done" is not the best word... The thing is that in the "Fields edit form", you can actually type text into the fields, and if you click "Save Defaults" it will leave that text as a default for that field, so when a visitor reaches the form, it will already have content filled in.
I am not sure about the unload protection... maybe it can be removed on both forms, however having the mechanism I just described, it may make sense for the "Fields edit form" to have it, but not the actions one.

**Comment by laulaz** [comment]
> @laulaz you can actually type text into the fields, and if you click "Save Defaults" it will leave that text as a default for that field, so when a visitor reaches the form, it will already have content filled in.
I understand the difference ... 

The "Save" button in actions listing is bound to `handleSaveDefaults`. So maybe we can just have a save button in both forms (calling `handleSaveDefaults`) with a redirect to the easyform in both cases ?  --> no need for the "Done" button 👍 


> it may make sense for the "Fields edit form" to have it, but not the actions one.
The actions form also has editable fields : if you change one of the checkbox --> then leave the page. Is it not the same need ?

**Comment by frapell** [comment]
@laulaz Alright, I standarized both form fields and form actions forms, they both only have a single "Save" button, which after saving changes will redirect back to the form, and they are both protected by the Unload protection

**Pull request merged**
