### PR TITLE
Backport PloneFormGen migration to 1.x (with changes)

### PR DESCRIPTION
**Pull request by gotcha**
I made the fixes suggested by @mauritsvanrees on @thomasmassmann branch.

IOW, this could override #278

### CODE REVIEW

**Review by jensens — APPROVED** [review]
I trust @gotcha and @thomasmassmann here. I would say go for merge.

**Review by mauritsvanrees — APPROVED** [review]
Thanks!

**Comment by mauritsvanrees** [comment]
Thanks for the work @thomasmassmann and @gotcha.

I saw no sense in doing yet another alpha release, so I went ahead and released this as 1.0.0.

**Comment by gotcha** [comment]
@mauritsvanrees Thanks for the merge and the release !

**Pull request merged**
