### PR TITLE
Batched savedataview

### PR DESCRIPTION
**Pull request by gianniftp**
The page loading of data collected by a **savedata adapter** containing a lot of rows is very time consuming and may raise a gateway error when using a load balancer.  
The savedata load an edit subform for **every** entry (so hundreds of editable subforms -> hundred-thousands html rows to load), but usually users just need the link to download the tsv file.
The fastest/simplest way to solve this was to set the batch_size in the SavedDataForm, to avoid loading all the items at once. 
This speed up the process and let the savedata be more usable.

### CODE REVIEW

**Comment by sauzher** [comment]
LGTM.
I think this could be merged into master too.

**Review by sauzher — APPROVED** [review]

**Comment by sauzher** [comment]
@alecpm I think this could be useful on #ump if there are save data adapters that need to be migrated from PFG.

**Comment by alecpm** [comment]
@sauzher Yes, I agree completely. We've had sites where forms were hit by spam bots which made the data views totally unusable until the entries were removed with a script.

**Comment by petschki** [comment]
What I would really like is that this batch value could be edited in the SaveDataAdapter add/edit form. See the schema: https://github.com/collective/collective.easyform/blob/master/src/collective/easyform/interfaces/savedata.py#L53 and that would also make sense for master of course!

**Comment by gianniftp** [comment]
The value can be now set from the SaveDataAdapter add/edit form, and the batching can be disabled if leaved blank or 0, according to @petschki suggestion.

**Review by petschki — APPROVED** [review]
Nearly perfect! Though a test would be great ;) Feel free to make a PR for master too ... I'll review it.

**Comment by gianniftp** [comment]
@petschki thanks for the feedback. I've added a validation check to the field to avoid negative numbers. 
I must admit i need some help to make an automated test, but i will try to prepare one.  Of course I've tested it "manually". 
I will also make a PR form master. thank you

**Review by mauritsvanrees — APPROVED** [review]
I tested it and it LGTM. Thanks!
I have added a test to show that it works and pushed a commit. Can you check that part?

And there have been test fixes on 3.x. And I have created PR #394 to fix some more. Can you review my PR? After it is merged, you can pull the changes into your branch (merge or rebase) and then we can see if all tests are fine.

I approve this, on the condition that the tests are green.

**Comment by mauritsvanrees** [comment]
I have merged 3.x in here.

**Pull request merged**
