### PR TITLE
Various fixes and enhacements from FHNW fork

### PR DESCRIPTION
**Pull request by tomgross**
This PR does several things:
* Add filesize validator
* Fixed issue with memcached as Zope RAM cache #32
* Allow subject fields to be multi-choice fields #71 
* Preserve newlines in mail fields pre, post and signature
* Cleanup old PFG test artifacts
* Port doctests to layered plone.testing tests

### CODE REVIEW

**Comment by tkimnguyen** [comment]
@tomgross did you see the build failures?

**Comment by tomgross** [comment]
@tkimnguyen I did but didn't have time to fix them 😉

**Comment by tomgross** [comment]
I consider this ready. Please review and merge.

**Comment by tomgross** [comment]
@agitator @jensens Could someone of you please review and merge. Thanks!

**Comment by jensens** [comment]
@tomgross it needs a rebase. When ready this one can be merged.

**Pull request merged**
