### PR TITLE
Use site email address if no recipient is specified

### PR DESCRIPTION
**Pull request by tmassman**
The current implementation was missing the recipient email address fallback for Plone 5. It was only implemented for the `from_address`.

The `ValueError` is still shown if there is no email address provided in the portal mail settings.

### CODE REVIEW

**Comment by prakharjoshi** [comment]
LGTM.

**Comment by tkimnguyen** [comment]
@tmassman can you make the change @jensens suggested?

**Comment by tmassman** [comment]
@tkimnguyen , I'll take a look.

**Comment by tmassman** [comment]
I'm sorry for the delay. I was very busy the last weeks.

**Comment by jensens** [comment]
@tmassman thanks for the patch!

**Pull request merged**
