### PR TITLE
Add support for Python 3

### LINKED ISSUE #128: Port collective.easyform to Python 3

### PR DESCRIPTION
**Pull request by pbauer**
Fixes #128

TODO: 
* [ ] Fix all tests 
* [x] Make sure it still works in py2

### CODE REVIEW

**Comment by petschki** [comment]
@pbauer getting near ... Plone 5.2/py2/py3 tests are green but Plone 5.1 and robot tests are currently deactivated ... stay tuned and DO NOT MERGE RIGHT NOW 😉

**Comment by petschki** [comment]
missing things for merge and release:

- [ ] rewrite robottests for Plone 5.1+ selectors (I did already a few)
- [ ] forceSSL redirect not working in 5.1 because testbrowser is not really logged out (still has `cmf.ModifyPortalContent` permission)
- [ ] investigate failing doctests for 5.1 (mentioned here #139 ) because of `ZPublisher.HTTPResponse.default_encoding = 'iso8859-15'`

the last one is weird because if you run your instance on 5.1 in a "real life browser" and navigate to the field view it works. Anybody has a hint how to fix this for the zope.testbrowser @jensens @davisagli ?

@djay if ok, we'll fix your pull request here and I'll close your's ...

**Comment by petschki** [comment]
If someone wants to put some love in the `todo_*.robot` tests feel free ... I'd recommend to merge and release this PR and make testing enhancements in a new PR.

/cc @pbauer @jensens

**Comment by jensens** [comment]
I agree, this can be merged. 

The version then needs to be increased on feature level. 

Since it is a massive change-set I would be super-safe and release first a RC. So, this can be field-tested and taken with a grain of salt.

**Comment by pbauer** [comment]
Thanks @petschki for seeing this through to the end 😄

**Comment by jensens** [comment]
and .... RELEASED https://pypi.org/project/collective.easyform/2.1.0rc1/

**Pull request merged**
