### PR TITLE
Add Advanced config to remove autofocus on firt input

### PR DESCRIPTION
**Pull request by yurj**
Add a checkbox to disable autofocus on the first input. It is enabled by default as is the default in Dexterity forms so it should not break anything.

### CODE REVIEW

**Review by ale-rt — COMMENTED** [review]
I am not using this package in these days, but the PR LGTM.

I see the `autofocus` field defaults to `True`, but this should not change anyones experience, given that:

https://github.com/plone/plone.app.z3cform/blob/ec706f171b684328c06423b49bf4fe37924c5961/plone/app/z3cform/templates/macros.pt#L88

P.s.: before merging, please add a changelog line.

Thanks for your contribution

**Comment by mauritsvanrees** [comment]
Seems fine.  But both with and without this PR I don't see autofocus working.  At least not in Firefox.

**Comment by yurj** [comment]
@mauritsvanrees you should see the pat-formautofocus class, the pattern depends on it. I've seen it working in FF but if it doesn't work in some cases, it should be a mockup issue.

@ale-rt I will add a changelog

**Comment by mauritsvanrees** [comment]
I have released `collective.easyform` 4.3.0 with this.

**Pull request merged**
