### PR TITLE
Possible fix for missing mail address from registry #33

### PR DESCRIPTION
**Pull request by tkimnguyen**
(also see discussion in https://github.com/collective/collective.easyform/pull/34)

### CODE REVIEW

**Comment by davilima6** [comment]
Nice! Remember to add an entry to the changelog.

**Comment by tkimnguyen** [comment]
@davilima6 done! or do I need to squash?

**Comment by jensens** [comment]
@tkimnguyen test are failing here

**Comment by tkimnguyen** [comment]
@jensens I never changed the tests so I don't know why they'd be failing. I can easily remove the extra trailing spaces though :)

**Pull request merged**
