### PR TITLE
Add Likert scale field

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by pbauer** [comment]
This is excellent! Only issue I found is that the saved-data is not displayed:
 
likert
 
Another small improvement would be if the whole table-cell would be clickable.

**Comment by pbauer** [comment]
@gotcha any chance you'll add these two missing features?

**Comment by gotcha** [comment]
@pbauer Gimme some time...

**Comment by gotcha** [comment]
@pbauer I did add what was needed to display saved data.

And made the whole table cell clickable.

CI is broken for seemingly unrelated issues.

**Pull request merged**
