### PR TITLE
restapi (de)serializers that include saved data

### PR DESCRIPTION
**Pull request by ThibautBorn**
context: was not possible to migrate saved data
with collective.exportimport

### CODE REVIEW

**Comment by MrTango** [comment]
> BEWARE: not registered by default in ZCML

why not?

and if not it should be at least added to the docs, or it does not exists ;)

**Comment by gotcha** [comment]
@MrTango I thought this is a breaking feature.

I guess making a proper version would solve that issue.

**Comment by laulaz** [comment]
@MrTango I propose to register the ZCML by default, but bump package version to 4.1.0 to make clear that old migration code can fail 😉 

I'm gonna review this tomorrow, if not already done by then !

**Comment by ThibautBorn** [comment]
We added some tests & registered the zcml

**Pull request merged**
