### PR TITLE
Fix Plone 5 actions - version 2

### PR DESCRIPTION
**Pull request by tomgross**
New PR because _improved_mailer_tests_ branch was merged to master already.
Obsoletes #35

### CODE REVIEW

**Comment by prakharjoshi** [comment]
@tomgross  why this travis-ci/push showing 403 ? Any idea on the last commit ?

**Comment by tomgross** [comment]
@prakharjoshi this is from an old build: https://travis-ci.org/collective/collective.easyform/builds/145189527 No new build was triggered meanwhile. I think we can safely ignore it. If you want to be sure. Push a test commit to the branch to trigger the build.

**Comment by prakharjoshi** [comment]
@tomgross  Thanks for clearing that doubt. :)

**Comment by davilima6** [comment]
This PR includes duplicate commits, for instance:

* 33b7d9a3941f29f6b2ba701868dce5d513f3d96f and ed2cb260c503a38a86e7c9a3ee9c788424dd3993
* a77d5bf73eb3e75d12469b19effbad9a954b216d and c35db35e7dd1389fbf2d20f2dab7863c4caa43ba

Also we should drop this test commit if possible: 73f76cbe8de9b667ca3845739d7fca061a4d2f4f

**Pull request merged**
