### PR TITLE
Fix display of widgets on thanks page in fieldsets

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
@agitator can you please review, merge and make a release?

**Comment by agitator** [comment]
is this also about https://github.com/collective/collective.easyform/issues/114 or what do I have to look for?

**Comment by tomgross** [comment]
Without this patch fields got rendered as HTML input fields on the thanks page. This PR fixes that.

**Comment by tomgross** [comment]
The form itself #114 is not affected.

**Comment by agitator** [comment]
new release https://pypi.org/project/collective.easyform/2.0.0b5/

**Pull request merged**
