### PR TITLE
Migration features 1.x

### PR DESCRIPTION
**Pull request by ThibautBorn**
migration from ploneformgen to easyform.
- better logging
- thankyou page
- better error management

### CODE REVIEW

**Comment by pbauer** [comment]
I use this branch to export PFG to be reimported as easyform in https://github.com/collective/collective.exportimport/#migrate-ploneformgen-to-easyform

Is that a good enough migration-story or do you need more? I found using in-place migration instead has no real benefits and is much slower.

**Comment by gotcha** [comment]
We have been running with in place migration for a while. The team will need to decide if they want to change this strategy.

**Comment by gotcha** [comment]
@pbauer Do you have any objection against merging this in 1.x ?

**Comment by pbauer** [comment]
Not at all

**Review by pbauer — APPROVED** [review]

**Pull request merged**
