### PR TITLE
Implement header injection

### PR DESCRIPTION
**Pull request by krissik**
see #146

### CODE REVIEW

**Comment by krissik** [comment]
Build is failing because the build for Plone 5.0.x does not know "Handle Alert"-Keyword (it is new in SeleniumLibrary 3.0 - see http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Handle%20Alert)

Should I remove it or is it possible to update SeleniumLibrary?

**Comment by agitator** [comment]
@krissik could you check why https://travis-ci.org/collective/collective.easyform/jobs/521615929 is failing?

**Comment by krissik** [comment]
https://travis-ci.org/collective/collective.easyform/jobs/521615929 is failing because of
"AssertionError: No keyword with name 'Handle Alert' found."

This is a new keyword in SeleniumLibrary 3.0. (see above)

Should I remove it or is it possible to update SeleniumLibrary?

**Comment by petschki** [comment]
@krissik I'd try updating SeleniumLibrary in `test-5.0.x.cfg` ... otherwise rewriting the robot test is maybe less expensive.

**Comment by krissik** [comment]
Ok.

Another question: Are robot tests taken into account for code coverage? (I am not happy that it decreased)

**Comment by petschki** [comment]
AFAIK coveralls doesn't know about robot tests. But if the tests are green, we can merge this even if coverage decreased ... don't worry, be happy 😉

**Comment by krissik** [comment]
Now all builds are green :-)

**Comment by petschki** [comment]
I've added a change note here https://github.com/collective/collective.easyform/commit/38b618af0a301c4d2158336cd1ee8adb2ce65f6e ... overlooked that ...

**Pull request merged**
