### PR TITLE
Add collective.z3cform.norobots integration

### PR DESCRIPTION
**Pull request by 1letter**
please check the p.r. , thats my first p.r. in the collective community.

### CODE REVIEW

**Comment by petschki** [comment]
Hi and thank's for your first PR! 🎉
You should add a note in the CHANGES.txt regarding your changes.

Unfortunately your changes doesn't work on Python 3 because `collective.z3cform.norobots` has an invalid relative import. On startup I get this error:

```
File "/Users/peterm/.buildout/eggs/collective.z3cform.norobots-1.4.4-py3.7.egg/collective/z3cform/norobots/__init__.py", line 3, in <module>
    from widget import NorobotsFieldWidget
```

Since we claim Python 3 compatibility on `master` you have two options:

 - fix  `c.z.norobots` and depend on the fixed version in `setup.py` here (shouldn't be that hard) or
 - make your PR not for `master` but instead for `1.x` branch which doesn't run on Py3

And please add `collective.z3cform.norobots` and `plone.formwidget.recaptcha` to the `[test]` extra_require, so that the tests are running with these features installed.

**Comment by petschki** [comment]
erm ... just noticed that `p.f.recaptcha` py3 compatibility is also in progress and still not released ...

**Comment by 1letter** [comment]
Ok, i close this p.r. and work on collective.z3cform.norobots and later when i'm finished, i submit a new p.r.

**Comment by petschki** [comment]
You can leave this open and give a label „in Progress“ ... then you dont have to do the work twice 👍🏼

**Pull request closed without merging**
