### PR TITLE
Schemaeditor UI: close modals and reload window when saving field(set)s

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
Yeah just checking this ... a few tests break because of the new password limit of 8 characters ...

**Comment by davisagli** [comment]
I recommend importing the current password from plone.app.testing instead
of hard coding it

**Comment by petschki** [comment]
jup ... I'll do ... thanks for the hint

**Review by frapell — APPROVED** [review]
LGTM

**Pull request merged**
